### ISSUE TITLE
Problems in getting this running on linux

### ISSUE THREAD

**Issue by Analect** [nearform/vidi-concorda-nodezoo-system#9]
Running this from a Virtualbox VM

```
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
Linux Kernel: 3.13.0-74-generic
Docker version 1.9.1, build a34a1d5
```

Wanted to run this up to get a feel for fuge. Not sure if it's officially released or not.
Followed instructions in readme .. pulling latest versions on named branches ...

At fuge prompt, ran `start all`
But whatever containers started, almost immediately crashed and attempted to restart. See logs below.

I'm not used to seeing IPs in this form:

```
 proxy elasticsearch 9200 -> 10.0.2.15:9200
  proxy elasticsearch 9300 -> 10.0.2.15:9300
  proxy influx 8086 -> 10.0.2.15:8086
  proxy influx 8083 -> 10.0.2.15:8083
```

Could it be that this is set up only to work on a mac?
Glad to try to troubleshoot, if someone can point me in the right direction.

Thanks.

I'm adding the terminal logs below: 

```
me@me-ubuntu-W520:~/Development/Tools/misc/fuge/vidi-concorda-nodezoo-system$ fuge shell system.yml 
compiling...
overriding run command for: mesh to: node ./system/base-node.js
overriding build command for: mesh to: cd system && npm install
overriding run command for: msgstats to: node ./system/msgstats.js
overriding build command for: msgstats to: cd system && npm install
overriding build command for: github to: npm install
overriding build command for: info to: npm install
overriding build command for: search to: npm install
overriding build command for: web to: npm install && npm run build
overriding build command for: concorda to: npm install && npm run build
overriding build command for: vidi to: npm install && npm run build
starting proxy...
  proxy elasticsearch 9200 -> 10.0.2.15:9200
  proxy elasticsearch 9300 -> 10.0.2.15:9300
  proxy influx 8086 -> 10.0.2.15:8086
  proxy influx 8083 -> 10.0.2.15:8083
starting shell..
? fuge> ps
name                           type            status          watch           tail            count
elasticsearch                  docker          stopped         no              no              0    
influx                         docker          stopped         no              no              0    
mesh                           process         stopped         no              no              0    
msgstats                       process         stopped         no              no              0    
github                         process         stopped         no              no              0    
info                           process         stopped         no              no              0    
npm                            process         stopped         no              no              0    
search                         process         stopped         no              no              0    
web                            process         stopped         no              no              0    
concorda                       process         stopped         no              no              0    
vidi                           process         stopped         no              no              0    
? fuge> start all
running: elasticsearch
running: influx
running: mesh
running: msgstats
running: github
running: info
running: npm
running: search
running: web
running: concorda
running: vidi
running: __proxy
? fuge> process exit [28423]: elasticsearch
process terminated unexpectedly [28423]: elasticsearch restarting
running: elasticsearch
process exit [28432]: influx
process terminated unexpectedly [28432]: influx restarting
running: influx
process exit [28562]: elasticsearch
process terminated unexpectedly [28562]: elasticsearch restarting
running: elasticsearch
process exit [28436]: github
process terminated unexpectedly [28436]: github restarting
running: github
process exit [28462]: web
process terminated unexpectedly [28462]: web restarting
running: web
process exit [28467]: concorda
process terminated unexpectedly [28467]: concorda restarting
running: concorda
process exit [28472]: vidi
process terminated unexpectedly [28472]: vidi restarting
running: vidi
process exit [28607]: influx
process terminated unexpectedly [28607]: influx restarting
running: influx
process exit [28608]: elasticsearch
process terminated unexpectedly [28608]: elasticsearch restarting
running: elasticsearch
client error: 8086 -> 10.0.2.15:8086 => EMFILE
please retry operation
process exit [28722]: influx
process terminated unexpectedly [28722]: influx restarting
running: influx


/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/util.js:94
    proc.child.stdout.pipe(stdOutStream);
                     ^

TypeError: Cannot read property 'pipe' of undefined
    at Object.streamOutput (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/util.js:94:22)
    at /home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:148:20
    at /home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/processRunner.js:121:11
    at run (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/processRunner.js:108:5)
    at Object.start (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/processRunner.js:120:9)
    at /home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/lib/system.js:135:25
    at /home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/async/lib/async.js:246:17
    at iterate (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/async/lib/async.js:146:13)
    at async.eachSeries (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/async/lib/async.js:162:9)
    at _asyncMap (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/fuge-runner/node_modules/async/lib/async.js:245:13)
```

**Comment by mcdonnelldean** [comment]
@Analect Indeed the system isn't fully ready yet but you should be able to at least run it to get a feel. Can you try removing this line:

https://github.com/nearform/vidi-concorda-nodezoo-system/blob/master/fuge-config.js#L4

And tell me if it runs? 

I am running with the assumption you have docker installed and can access it in the same terminal you are running fuge in? `docker ps -a` should return some input (or empty table)

**Comment by Analect** [comment]
@mcdonnelldean 
Yes ... I can access docker from the same terminal ... but obviously not from within the fuge prompt.

I removed that line 4 as you suggested and re-ran `start all` from the fuge prompt.  I can now see two containers related to this with `docker ps` form another terminal.

```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                            NAMES
a7aa8b5d146a        tutum/influxdb:0.9     "/run.sh"                37 seconds ago      Up 35 seconds       0.0.0.0:8083->8083/tcp, 0.0.0.0:8086->8086/tcp   loving_hopper
a0bee7b96099        elasticsearch          "/docker-entrypoint.s"   37 seconds ago      Up 36 seconds       0.0.0.0:9200->9200/tcp, 0.0.0.0:9300->9300/tcp   naughty_saha
```

The `fuge shell system.yml` command appeared to run smoother this time ... although there's a slight delay in getting a response from the fuge prompt returned ... hence the repeated `pspsps` at the end.

```
fuge shell system.yml 
compiling...
overriding run command for: mesh to: node ./system/base-node.js
overriding build command for: mesh to: cd system && npm install
overriding run command for: msgstats to: node ./system/msgstats.js
overriding build command for: msgstats to: cd system && npm install
overriding build command for: github to: npm install
overriding build command for: info to: npm install
overriding build command for: search to: npm install
overriding build command for: web to: npm install && npm run build
overriding build command for: concorda to: npm install && npm run build
overriding build command for: vidi to: npm install && npm run build
starting proxy...
starting shell..
? fuge> ps
name                           type            status          watch           tail            count
elasticsearch                  docker          stopped         no              no              0    
influx                         docker          stopped         no              no              0    
mesh                           process         stopped         no              no              0    
msgstats                       process         stopped         no              no              0    
github                         process         stopped         no              no              0    
info                           process         stopped         no              no              0    
npm                            process         stopped         no              no              0    
search                         process         stopped         no              no              0    
web                            process         stopped         no              no              0    
concorda                       process         stopped         no              no              0    
vidi                           process         stopped         no              no              0   

? fuge> start all
running: elasticsearch
running: influx
running: mesh
running: msgstats
running: github
running: info
running: npm
running: search
running: web
running: concorda
running: vidi
running: __proxy
? fuge> pspsps
```

However, after a few seconds, fuge begins to act-up again.

```
process exit [28974]: github
process terminated unexpectedly [28974]: github restarting
running: github
process exit [28996]: web
process terminated unexpectedly [28996]: web restarting
running: web
process exit [29001]: concorda
process terminated unexpectedly [29001]: concorda restarting
running: concorda
process exit [29006]: vidi
process terminated unexpectedly [29006]: vidi restarting
running: vidi
process exit [29231]: github
process terminated unexpectedly [29231]: github restarting
running: github
process exit [29232]: web
process terminated unexpectedly [29232]: web restarting
running: web
process exit [29237]: concorda
process terminated unexpectedly [29237]: concorda restarting
running: concorda
process exit [29242]: vidi
process terminated unexpectedly [29242]: vidi restarting
running: vidi
process exit [29251]: github
process terminated unexpectedly [29251]: github restarting
running: github


events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: watch ../nodezoo-github/node_modules/level-delete-range/LICENCE ENOSPC
    at exports._errnoException (util.js:860:11)
    at FSWatcher.start (fs.js:1313:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/me/.nvm/versions/node/v5.0.0/lib/node_modules/fuge/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by mcdonnelldean** [comment]
Interesting, could could dump the logs for each system? They get generated in ./logs and clear down on each restart.

**Comment by Analect** [comment]
I think you are after these?
![image](https://cloud.githubusercontent.com/assets/4063815/12785536/dd7fd01e-ca84-11e5-8062-18a266d07a47.png)

See if this works.
[fuge_log.zip](https://github.com/nearform/vidi-concorda-nodezoo-system/files/115810/fuge_log.zip)

**Comment by mcdonnelldean** [comment]
Looks like a bug on our end around Mesh, can you give me a day or so to check this out?

**Comment by Analect** [comment]
No problem. Just post back here and I can give it another try as and when.
